# Generated by Django 3.1.2 on 2021-09-16 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grocery',
            options={'verbose_name': 'grocerie'},
        ),
        migrations.AlterField(
            model_name='grocery',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 10, 7, 59, 824834)),
        ),
    ]
