# Generated by Django 3.1.2 on 2021-09-17 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='time',
            field=models.DateField(default=datetime.date(2021, 9, 17), null=True),
        ),
    ]
