# Generated by Django 3.1.2 on 2021-09-17 12:33

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grocery_app', '0002_auto_20210917_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='time',
            field=models.DateField(default=datetime.datetime(2021, 9, 17, 12, 33, 14, 455408), null=True),
        ),
        migrations.AlterUniqueTogether(
            name='grocerylist',
            unique_together={('user', 'time')},
        ),
    ]
