# Generated by Django 3.1.2 on 2021-09-16 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0002_auto_20210916_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grocery',
            old_name='weight',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='grocery',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 10, 9, 10, 438528)),
        ),
    ]
