# Generated by Django 3.1.2 on 2021-09-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0003_auto_20210917_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='time',
        ),
    ]
