# Generated by Django 3.1.2 on 2021-09-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0004_remove_grocery_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grocerylist',
            unique_together=set(),
        ),
    ]
